"""empty message

Revision ID: 13017a2a8ff5
Revises: e4fe594f74fd
Create Date: 2020-03-07 23:47:13.845133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13017a2a8ff5'
down_revision = 'e4fe594f74fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###
